Repository SwengGolfTeam/Sweng_Golf, pull requests merged in 2018-11, with the labels that each got.

#93 Fb answer offer
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/CreateOfferActivityTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/DeleteOfferTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/ShowOfferActivityDbNotWorkingTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/ShowOfferActivityTest.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/Database.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/Answer.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/Answers.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/ListAnswerAdapter.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/ListOfferAdapter.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/Offer.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/ShowOfferActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/preference/ListPreferenceAdapter.java
  app/src/main/java/ch/epfl/sweng/swenggolf/tools/ThreeFieldsViewHolder.java
  app/src/main/res/drawable/ic_favorite.xml
  app/src/main/res/drawable/ic_favorite_border.xml
  app/src/main/res/layout/activity_show_offer.xml
  app/src/main/res/layout/layout_header.xml
  app/src/main/res/layout/offers_list_row.xml
  app/src/main/res/layout/reaction_you.xml
  app/src/main/res/layout/reactions_others.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#108 Fb offer picture capture
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/CreateOfferActivityTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/CreateOfferPhotoTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/StorageTest.java
  app/src/main/AndroidManifest.xml
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/CreateOfferActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/ShowOfferActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/storage/Storage.java
  app/src/main/res/layout/activity_create_offer.xml
  app/src/main/res/xml/file_paths.xml
Labels: enhancement

#112 Fix photo capture storage issue
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/CreateOfferActivity.java
Labels: bug

#109 Fb my offers
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/ListOwnOfferActivityTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/MainMenuActivityInstrumentedTestIntents.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/AttributeFilter.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/Database.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/FakeDatabase.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/FireDatabase.java
  app/src/main/java/ch/epfl/sweng/swenggolf/main/MainMenuActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/CreateOfferActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/DatabaseOfferConsumer.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/ListOfferActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/ListOwnOfferActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/storage/Storage.java
  app/src/main/res/drawable-hdpi/baseline_library_books_black_18.png
  app/src/main/res/drawable-hdpi/baseline_library_books_black_24.png
  app/src/main/res/drawable-hdpi/baseline_library_books_black_36.png
  app/src/main/res/drawable-hdpi/baseline_library_books_black_48.png
  app/src/main/res/drawable-mdpi/baseline_library_books_black_18.png
  app/src/main/res/drawable-mdpi/baseline_library_books_black_24.png
  app/src/main/res/drawable-mdpi/baseline_library_books_black_36.png
  app/src/main/res/drawable-mdpi/baseline_library_books_black_48.png
  app/src/main/res/drawable-xhdpi/baseline_library_books_black_18.png
  app/src/main/res/drawable-xhdpi/baseline_library_books_black_24.png
  app/src/main/res/drawable-xhdpi/baseline_library_books_black_36.png
  app/src/main/res/drawable-xhdpi/baseline_library_books_black_48.png
  app/src/main/res/drawable-xxhdpi/baseline_library_books_black_18.png
  app/src/main/res/drawable-xxhdpi/baseline_library_books_black_24.png
  app/src/main/res/drawable-xxhdpi/baseline_library_books_black_36.png
  app/src/main/res/drawable-xxhdpi/baseline_library_books_black_48.png
  app/src/main/res/drawable-xxxhdpi/baseline_library_books_black_18.png
  app/src/main/res/drawable-xxxhdpi/baseline_library_books_black_24.png
  app/src/main/res/drawable-xxxhdpi/baseline_library_books_black_36.png
  app/src/main/res/drawable-xxxhdpi/baseline_library_books_black_48.png
  app/src/main/res/drawable/baseline_library_books_24.xml
  app/src/main/res/menu/menu_drawer.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/ch/epfl/sweng/swenggolf/AttributeFilterTest.java
  app/src/test/java/ch/epfl/sweng/swenggolf/FakeDatabaseTest.java
Labels: enhancement

#110 Fb local database
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/CategoriesMenuTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/ListOfferActivityTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/LocalDatabaseTest.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/LocalDatabase.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/Category.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/ListOfferActivity.java
Labels: enhancement

#111 Better answers
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/AnswersTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/DeleteOfferTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/ShowOfferActivityDbNotWorkingTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/ShowOfferActivityTest.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/ListAnswerAdapter.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/ShowOfferActivity.java
  app/src/main/res/layout/activity_show_offer.xml
  app/src/main/res/layout/reaction_you.xml
  app/src/main/res/layout/reactions_others.xml
  app/src/main/res/values/strings.xml
Labels: improvement

#107 Adding the possibility to localize an offer
  .travis.yml
  app/build.gradle
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/AnswersTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/CreateOfferActivityTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/ShowOfferActivityTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/TestUtility.java
  app/src/main/AndroidManifest.xml
  app/src/main/java/ch/epfl/sweng/swenggolf/Config.java
  app/src/main/java/ch/epfl/sweng/swenggolf/Permission.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/FilledFakeDatabase.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/SignInActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/location/AppLocation.java
  app/src/main/java/ch/epfl/sweng/swenggolf/location/ConcreteLocation.java
  app/src/main/java/ch/epfl/sweng/swenggolf/location/FakeLocation.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/CreateOfferActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/Offer.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/ShowOfferActivity.java
  app/src/main/res/drawable/baseline_library_books_24.xml
  app/src/main/res/drawable/ic_arrow_back.xml
  app/src/main/res/drawable/ic_baseline_arrow_back_24px.xml
  app/src/main/res/drawable/ic_favorite.xml
  app/src/main/res/drawable/ic_favorite_border.xml
  app/src/main/res/drawable/ic_menu_black_24dp.xml
  app/src/main/res/layout/activity_create_offer.xml
  app/src/main/res/layout/activity_edit_profile.xml
  app/src/main/res/layout/activity_list_offer.xml
  app/src/main/res/layout/activity_main_menu.xml
  app/src/main/res/layout/activity_main_wrapper.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/activity_show_offer.xml
  app/src/main/res/layout/activity_waiting.xml
  app/src/main/res/layout/offers_list_row.xml
  app/src/main/res/layout/reaction_you.xml
  app/src/main/res/layout/reactions_others.xml
  app/src/main/res/layout/switch_item.xml
  app/src/main/res/menu/menu_drawer.xml
  app/src/main/res/menu/menu_empty.xml
  app/src/main/res/menu/menu_list_offer.xml
  app/src/main/res/menu/menu_show_offer.xml
  app/src/main/res/values/integers.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/file_paths.xml
  app/src/test/java/ch/epfl/sweng/swenggolf/AttributeFilterTest.java
  app/src/test/java/ch/epfl/sweng/swenggolf/ConcreteLocationTest.java
  app/src/test/java/ch/epfl/sweng/swenggolf/ConfigTest.java
  app/src/test/java/ch/epfl/sweng/swenggolf/FakeDatabaseTest.java
  app/src/test/java/ch/epfl/sweng/swenggolf/FakeStorageTest.java
  app/src/test/java/ch/epfl/sweng/swenggolf/UserTest.java
Labels: enhancement

#117 Revert travis gradlew to info
  .travis.yml
Labels: bug

#106 Create an expiration date for your offer
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/CreateOfferActivityTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/ParcelableTest.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/FilledFakeDatabase.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/CreateOfferActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/Offer.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/ShowOfferActivity.java
  app/src/main/res/layout/activity_create_offer.xml
  app/src/main/res/layout/activity_show_offer.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/ch/epfl/sweng/swenggolf/OfferTest.java
Labels: enhancement, not ready

#128 Change icon
  app/src/main/AndroidManifest.xml
  app/src/main/ic_launcher-web.png
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/values/ic_launcher_background.xml
Labels: UX/UI, enhancement

#129 Add Points To User
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/AnswersTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/CategoriesMenuTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/CreateOfferActivityTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/CreateUserActivityTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/ListOfferActivityTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/ListOwnOfferActivityTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/MainMenuActivityInstrumentedTestAvailable.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/ParcelableTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/PreferenceActivityTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/ProfileActivityOtherUserTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/ProfileActivityTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/ShowOfferActivityDbNotWorkingTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/ShowOfferActivityTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/WaitingActivityTest.java
  app/src/main/java/ch/epfl/sweng/swenggolf/Config.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/CreateUserActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/DatabaseUser.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/FilledFakeDatabase.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/WaitingActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/main/MainMenuActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/CreateOfferActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/ListAnswerAdapter.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/ShowOfferActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/preference/ListPreferenceAdapter.java
  app/src/main/java/ch/epfl/sweng/swenggolf/profile/EditProfileActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/profile/PointType.java
  app/src/main/java/ch/epfl/sweng/swenggolf/profile/ProfileActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/profile/User.java
  app/src/main/java/ch/epfl/sweng/swenggolf/tools/FragmentConverter.java
  app/src/main/java/ch/epfl/sweng/swenggolf/tools/ViewUserFiller.java
  app/src/test/java/ch/epfl/sweng/swenggolf/ConfigTest.java
  app/src/test/java/ch/epfl/sweng/swenggolf/TestHelper.java
  app/src/test/java/ch/epfl/sweng/swenggolf/UserTest.java
Labels: enhancement

#116 Fix a bug in ShowOfferActivity
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/AnswersTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/ShowOfferActivityTest.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/CreateUserActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/Database.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/FilledFakeDatabase.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/LocalDatabase.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/WaitingActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/main/MainMenuActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/Category.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/CreateOfferActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/DatabaseOfferConsumer.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/ListAnswerAdapter.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/ListOfferActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/Offer.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/ShowOfferActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/preference/ListPreferenceAdapter.java
  app/src/main/java/ch/epfl/sweng/swenggolf/profile/EditProfileActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/profile/PointType.java
  app/src/main/java/ch/epfl/sweng/swenggolf/profile/User.java
  app/src/main/java/ch/epfl/sweng/swenggolf/tools/FragmentConverter.java
  app/src/main/java/ch/epfl/sweng/swenggolf/tools/ViewUserFiller.java
  app/src/main/res/values/strings.xml
Labels: bug

#131 Add a new function to Database to read entries sorted
  app/src/main/java/ch/epfl/sweng/swenggolf/database/AttributeOrdering.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/Database.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/FakeDatabase.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/FireDatabase.java
  app/src/test/java/ch/epfl/sweng/swenggolf/AttributeOrderingTest.java
  app/src/test/java/ch/epfl/sweng/swenggolf/FakeDatabaseTest.java
  app/src/test/java/ch/epfl/sweng/swenggolf/FireDatabaseTest.java
Labels: improvement

#134 Fb profile badge
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/ListAnswerAdapter.java
  app/src/main/java/ch/epfl/sweng/swenggolf/profile/Badge.java
  app/src/main/java/ch/epfl/sweng/swenggolf/profile/ProfileActivity.java
  app/src/main/res/drawable/badge00.png
  app/src/main/res/drawable/badge01.png
  app/src/main/res/drawable/badge02.png
  app/src/main/res/drawable/badge03.png
  app/src/main/res/drawable/badge04.png
  app/src/main/res/drawable/badge05.png
  app/src/main/res/drawable/badge06.png
  app/src/main/res/drawable/badge07.png
  app/src/main/res/drawable/badge08.png
  app/src/main/res/drawable/badge09.png
  app/src/main/res/drawable/badge10.png
  app/src/main/res/drawable/badge11.png
  app/src/main/res/drawable/badge12.png
  app/src/main/res/drawable/badge13.png
  app/src/main/res/drawable/badge14.png
  app/src/main/res/drawable/badge15.png
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/ch/epfl/sweng/swenggolf/BadgeTest.java
Labels: UX/UI, enhancement

#136 Fb notifications
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/AnswersTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/NotificationsDbNotWorkingTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/NotificationsTest.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/Database.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/FilledFakeDatabase.java
  app/src/main/java/ch/epfl/sweng/swenggolf/main/MainMenuActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/notification/ItemClickListener.java
  app/src/main/java/ch/epfl/sweng/swenggolf/notification/Notification.java
  app/src/main/java/ch/epfl/sweng/swenggolf/notification/NotificationManager.java
  app/src/main/java/ch/epfl/sweng/swenggolf/notification/NotificationType.java
  app/src/main/java/ch/epfl/sweng/swenggolf/notification/NotificationsActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/notification/NotificationsAdapter.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/ListAnswerAdapter.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/ShowOfferActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/profile/ProfileActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/tools/ThreeFieldsViewHolder.java
  app/src/main/res/drawable/ic_clear_black_24dp.xml
  app/src/main/res/drawable/ic_comment_black_24dp.xml
  app/src/main/res/drawable/ic_exposure_plus_1_black_24dp.xml
  app/src/main/res/drawable/ic_favorite_black_24dp.xml
  app/src/main/res/drawable/ic_notifications_active_black_24dp.xml
  app/src/main/res/drawable/ic_star_black_24dp.xml
  app/src/main/res/layout/activity_notifications.xml
  app/src/main/res/layout/notification.xml
  app/src/main/res/menu/menu_drawer.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#140 Ui new reputation portraits
  app/src/main/java/ch/epfl/sweng/swenggolf/profile/Badge.java
  app/src/main/res/drawable/badge00.png
  app/src/main/res/drawable/badge01.png
  app/src/main/res/drawable/badge02.png
  app/src/main/res/drawable/badge03.png
  app/src/main/res/drawable/badge04.png
  app/src/main/res/drawable/badge05.png
  app/src/main/res/drawable/badge06.png
  app/src/main/res/drawable/badge07.png
  app/src/main/res/drawable/badge08.png
  app/src/main/res/drawable/badge09.png
  app/src/main/res/drawable/badge10.png
  app/src/main/res/drawable/badge11.png
  app/src/main/res/drawable/badge12.png
  app/src/main/res/drawable/badge13.png
  app/src/main/res/drawable/badge14.png
  app/src/main/res/drawable/badge15.png
  app/src/test/java/ch/epfl/sweng/swenggolf/BadgeTest.java
Labels: UX/UI, improvement

#151 Fix javadoc
  app/src/main/java/ch/epfl/sweng/swenggolf/Leaderboard.java
  app/src/main/java/ch/epfl/sweng/swenggolf/LeaderboardAdapter.java
  app/src/main/java/ch/epfl/sweng/swenggolf/Permission.java
  app/src/main/java/ch/epfl/sweng/swenggolf/UserListener.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/AttributeFilter.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/Database.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/DatabaseUser.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/DbError.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/FakeDatabase.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/FilledFakeDatabase.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/FireDatabase.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/LocalDatabase.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/SignInActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/ValueListener.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/WaitingActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/location/AppLocation.java
  app/src/main/java/ch/epfl/sweng/swenggolf/location/ConcreteLocation.java
  app/src/main/java/ch/epfl/sweng/swenggolf/location/FakeLocation.java
  app/src/main/java/ch/epfl/sweng/swenggolf/main/MainMenuActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/notification/ItemClickListener.java
  app/src/main/java/ch/epfl/sweng/swenggolf/notification/Notification.java
  app/src/main/java/ch/epfl/sweng/swenggolf/notification/NotificationManager.java
  app/src/main/java/ch/epfl/sweng/swenggolf/notification/NotificationType.java
  app/src/main/java/ch/epfl/sweng/swenggolf/notification/NotificationsActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/notification/NotificationsAdapter.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/Answer.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/Answers.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/Category.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/ListAnswerAdapter.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/ListOfferActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/ListOfferAdapter.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/ListOfferTouchListener.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/ListOwnOfferActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/Offer.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/ShowOfferActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/create/CreateHelper.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/create/CreateListeners.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/create/CreateOfferActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/preference/ListPreferenceAdapter.java
  app/src/main/java/ch/epfl/sweng/swenggolf/preference/ListPreferencesActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/profile/Badge.java
  app/src/main/java/ch/epfl/sweng/swenggolf/profile/EditProfileActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/profile/PointType.java
  app/src/main/java/ch/epfl/sweng/swenggolf/profile/ProfileActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/profile/User.java
  app/src/main/java/ch/epfl/sweng/swenggolf/storage/FakeStorage.java
  app/src/main/java/ch/epfl/sweng/swenggolf/storage/FireStorage.java
  app/src/main/java/ch/epfl/sweng/swenggolf/storage/Storage.java
  app/src/main/java/ch/epfl/sweng/swenggolf/tools/Check.java
  app/src/main/java/ch/epfl/sweng/swenggolf/tools/FragmentConverter.java
  app/src/main/java/ch/epfl/sweng/swenggolf/tools/ThreeFieldsViewHolder.java
  app/src/main/java/ch/epfl/sweng/swenggolf/tools/ViewUserFiller.java
Labels: improvement

#155 Add read and write functions for level in local db
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/LocalDatabaseTest.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/LocalDatabase.java
Labels: improvement

#153 Create New type of button and change the sign-in activity appearance
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/CreateUserActivityTest.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/CreateUserActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/Answer.java
  app/src/main/res/drawable/btn_rounded.xml
  app/src/main/res/drawable/btn_slightly_rounded.xml
  app/src/main/res/drawable/help.jpg
  app/src/main/res/layout/activity_create_offer.xml
  app/src/main/res/layout/activity_create_user.xml
  app/src/main/res/layout/activity_edit_profile.xml
  app/src/main/res/layout/activity_show_offer.xml
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/layout/reaction_you.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: improvement

#156 Fb can not accept own answer
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/AnswersTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/PointGainTest.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/Answers.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/ListAnswerAdapter.java
Labels: improvement

#159 Fix display of title and author in list offers
  app/src/main/res/layout/offers_list_row.xml
Labels: UX/UI, bug

#160 Fix username behaviour on list of offers
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/CategoriesMenuTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/ListOfferActivityTest.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/ListOfferActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/ListOfferAdapter.java
  app/src/main/java/ch/epfl/sweng/swenggolf/tools/ViewUserFiller.java
Labels: bug

#157 Fb better notifications
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/NotificationsTest.java
  app/src/main/java/ch/epfl/sweng/swenggolf/notification/Notification.java
  app/src/main/java/ch/epfl/sweng/swenggolf/notification/NotificationType.java
  app/src/main/java/ch/epfl/sweng/swenggolf/notification/NotificationsActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/notification/NotificationsAdapter.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/ShowOfferActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/profile/Badge.java
  app/src/main/res/layout/notification.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/ch/epfl/sweng/swenggolf/BadgeTest.java
Labels: improvement

#162 Fix menu in leaderboard and infinite filling
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/LeaderboardTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/MainMenuActivityInstrumentedTestIntents.java
  app/src/main/java/ch/epfl/sweng/swenggolf/leaderboard/Leaderboard.java
  app/src/main/java/ch/epfl/sweng/swenggolf/leaderboard/LeaderboardAdapter.java
  app/src/main/java/ch/epfl/sweng/swenggolf/main/MainMenuActivity.java
Labels: UX/UI, bug

#166 Cc add additional tests
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/ShowOfferActivityTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/WaitingActivityTest.java
Labels: code coverage, not ready

#165 Fb profile from answer
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/AnswersTest.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/ShowOfferActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/answer/Answer.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/answer/Answers.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/answer/ListAnswerAdapter.java
  app/src/main/res/layout/activity_show_offer.xml
Labels: improvement
