Repository SwengGolfTeam/Sweng_Golf, pull requests merged in 2018-12, with the labels that each got.

#178 Implement the individual lists
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/ProfileActivityOtherUserTest.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/ListOwnOfferActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/profile/ProfileActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/profile/User.java
  app/src/main/java/ch/epfl/sweng/swenggolf/tools/FragmentConverter.java
  app/src/main/res/layout/activity_profile.xml
  app/src/test/java/ch/epfl/sweng/swenggolf/FakeDatabaseTest.java
Labels: enhancement

#179 Fb search offers
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/CategoriesMenuTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/ListOfferActivityTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/NavigationTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/SearchOffersTests.java
  app/src/main/AndroidManifest.xml
  app/src/main/java/ch/epfl/sweng/swenggolf/database/FakeDatabaseListHandler.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/FilledFakeDatabase.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/ListOfferActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/ListOfferAdapter.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/create/CreatePictureHelper.java
  app/src/main/java/ch/epfl/sweng/swenggolf/tools/FragmentConverter.java
  app/src/main/res/layout/activity_list_offer.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#176 Fb messaging
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/MessagingTest.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/Database.java
  app/src/main/java/ch/epfl/sweng/swenggolf/messaging/MessagesAdapter.java
  app/src/main/java/ch/epfl/sweng/swenggolf/messaging/MessagingActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/ShowOfferActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/answer/Answer.java
  app/src/main/java/ch/epfl/sweng/swenggolf/tools/FragmentConverter.java
  app/src/main/res/drawable/ic_send_white_24dp.xml
  app/src/main/res/layout/activity_messaging.xml
  app/src/main/res/layout/activity_show_offer.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#181 Fix bug preventing expansion of offers in list
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/ListOfferActivityTest.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/ListOfferActivity.java
Labels: bug

#182 Fb internet banner
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/ListOfferActivityTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/NavigationTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/OfflineTests.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/SignInActivityTest.java
  app/src/main/AndroidManifest.xml
  app/src/main/java/ch/epfl/sweng/swenggolf/Config.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/FireDatabase.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/SignInActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/location/AppLocation.java
  app/src/main/java/ch/epfl/sweng/swenggolf/main/MainMenuActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/network/Network.java
  app/src/main/java/ch/epfl/sweng/swenggolf/network/NetworkReceiver.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/ListOfferActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/create/CreateHelper.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/create/CreateOfferActivity.java
  app/src/main/res/layout/activity_main_menu.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: UX/UI, bug

#199 Fx offer display
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/AnswersTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/CloseOfferTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/CreateOfferActivityTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/MessagingTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/NotificationsTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/PointGainTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/ShowOfferActivityDbNotWorkingTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/ShowOfferActivityTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/TestUtility.java
  app/src/main/res/layout/activity_show_offer.xml
  app/src/main/res/layout/reaction_you.xml
  app/src/main/res/layout/reactions_others.xml
Labels: improvement

#198 Fb save offer
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/NavigationTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/SavePartialOfferTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/TestUtility.java
  app/src/main/java/ch/epfl/sweng/swenggolf/Config.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/Database.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/FakeDatabase.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/FireDatabase.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/SignInActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/location/AppLocation.java
  app/src/main/java/ch/epfl/sweng/swenggolf/main/MainMenuActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/messaging/MessagingActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/ListOfferActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/ListOfferAdapter.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/Offer.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/ShowOfferActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/answer/Answer.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/create/CreateHelper.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/create/CreateListeners.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/create/CreateOfferActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/tools/FragmentConverter.java
  app/src/main/res/values/strings.xml
Labels: enhancement

#201 Fix the profile layout
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/ProfileActivityOtherUserTest.java
  app/src/main/res/layout/activity_profile.xml
Labels: UX/UI

#204 Add onResume function call
  app/src/main/java/ch/epfl/sweng/swenggolf/main/MainMenuActivity.java
Labels: bug

#205 Fb add nb views for offers
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/AnswersTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/CreateOfferActivityTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/MessagingTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/NavigationTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/PointGainTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/ProfileActivityTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/ShowOfferActivityDbNotWorkingTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/ShowOfferStatsTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/TestUtility.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/Database.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/DbError.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/FilledFakeDatabase.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/FireDatabase.java
  app/src/main/java/ch/epfl/sweng/swenggolf/main/MainMenuActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/ShowOfferActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/create/CreateHelper.java
  app/src/main/java/ch/epfl/sweng/swenggolf/statistics/OfferStats.java
  app/src/main/res/layout/activity_show_offer.xml
Labels: enhancement

#200 Fix error text recyclerview
  app/src/main/java/ch/epfl/sweng/swenggolf/leaderboard/Leaderboard.java
  app/src/main/java/ch/epfl/sweng/swenggolf/notification/NotificationsActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/ShowOfferActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/list/ListOfferActivity.java
  app/src/main/res/layout/dialog_custom_layout.xml
Labels: bug

#206 Add activity and layout for statistics
  app/google-services.json
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/LeaderboardTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/ListOfferActivityTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/ListOwnOfferActivityTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/MainMenuActivityInstrumentedTestAvailable.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/MessagingTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/OfflineTests.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/SavePartialOfferTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/SearchOffersTests.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/ShowOfferActivityTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/ShowOfferStatsTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/SignInActivityTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/UserStatsActivityTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/WaitingActivityTest.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/CreateUserActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/Database.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/DatabaseUser.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/FakeDatabase.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/FilledFakeDatabase.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/WaitingActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/main/MainMenuActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/messaging/MessagingActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/ShowOfferActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/answer/ListAnswerAdapter.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/create/CreateOfferActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/statistics/OfferStats.java
  app/src/main/java/ch/epfl/sweng/swenggolf/statistics/StatisticsActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/statistics/StatisticsAdapter.java
  app/src/main/java/ch/epfl/sweng/swenggolf/statistics/UserStats.java
  app/src/main/java/ch/epfl/sweng/swenggolf/tools/FragmentConverter.java
  app/src/main/java/ch/epfl/sweng/swenggolf/tools/TwoFieldsViewHolder.java
  app/src/main/res/layout/activity_statistics.xml
  app/src/main/res/layout/statistics.xml
  app/src/main/res/menu/menu_drawer.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/ch/epfl/sweng/swenggolf/DatabaseTest.java
  app/src/test/java/ch/epfl/sweng/swenggolf/FakeDatabaseTest.java
Labels: enhancement

#208 Fb friends notifications
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/NotificationsTest.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/Database.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/FakeDatabase.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/FakeDatabaseListHandler.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/FireDatabase.java
  app/src/main/java/ch/epfl/sweng/swenggolf/notification/NotificationType.java
  app/src/main/java/ch/epfl/sweng/swenggolf/notification/NotificationsAdapter.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/create/CreateHelper.java
  app/src/main/java/ch/epfl/sweng/swenggolf/preference/ListPreferenceAdapter.java
  app/src/main/res/values/strings.xml
  app/src/test/java/ch/epfl/sweng/swenggolf/FireDatabaseTest.java
Labels: enhancement, not ready

#207 Fb offer template
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/ListOfferActivityTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/ListOfferAdapterTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/MainMenuActivityInstrumentedTestIntents.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/MessagingTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/NavigationTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/NotificationsTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/OfferPatternTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/OfflineTests.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/PointGainTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/SavePartialOfferTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/SearchOffersTests.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/SignInActivityTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/TestUtility.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/WaitingActivityTest.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/Database.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/FakeDatabase.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/FilledFakeDatabase.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/FireDatabase.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/create/CreateHelper.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/create/CreateListeners.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/create/CreateOfferActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/list/ListOfferActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/list/ListOfferAdapter.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/list/own/ListOwnOfferActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/list/own/ListOwnOfferPager.java
  app/src/main/res/layout/activity_create_offer.xml
  app/src/main/res/layout/save_offer_pattern.xml
  app/src/main/res/menu/menu_create_offer.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/ch/epfl/sweng/swenggolf/FakeDatabaseTest.java
  app/src/test/java/ch/epfl/sweng/swenggolf/FireDatabaseTest.java
Labels: enhancement

#211 Fb notification other answers
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/NotificationsTest.java
  app/src/main/java/ch/epfl/sweng/swenggolf/notification/NotificationType.java
  app/src/main/java/ch/epfl/sweng/swenggolf/notification/NotificationsAdapter.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/ShowOfferActivity.java
  app/src/main/res/values/strings.xml
Labels: improvement

#210 Correct error message for answers and messages
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/MessagingDbNotWorkingTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/MessagingTest.java
  app/src/main/java/ch/epfl/sweng/swenggolf/messaging/MessagingActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/ShowOfferActivity.java
  app/src/main/res/layout/activity_show_offer.xml
  app/src/main/res/values/strings.xml
Labels: bug, improvement

#215 Miscellaneous fixes for the project
  README.md
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/CloseOfferTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/CreateOfferFragmentTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/CreateOfferPhotoTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/ListOfferFragmentTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/ListOwnOfferFragmentTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/MainMenuActivityInstrumentedTestIntents.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/NavigationTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/NotificationsDbNotWorkingTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/NotificationsTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/OfferPatternTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/PointGainTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/PreferenceFragmentTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/ProfileFragmentOtherUserTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/ProfileFragmentTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/SavePartialOfferTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/SearchOffersTests.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/ShowOfferFragmentDbNotWorkingTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/ShowOfferFragmentTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/TestUtility.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/FireDatabase.java
  app/src/main/java/ch/epfl/sweng/swenggolf/main/MainMenuActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/messaging/MessagingFragment.java
  app/src/main/java/ch/epfl/sweng/swenggolf/notification/NotificationsAdapter.java
  app/src/main/java/ch/epfl/sweng/swenggolf/notification/NotificationsFragment.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/ShowOfferFragment.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/create/CreateHelper.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/create/CreateListeners.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/create/CreateOfferFragment.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/list/ListOfferFragment.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/list/own/ListOwnOfferFragment.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/list/own/ListOwnOfferPager.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/list/own/ListOwnOfferTabFragment.java
  app/src/main/java/ch/epfl/sweng/swenggolf/preference/ListFollowersAdapter.java
  app/src/main/java/ch/epfl/sweng/swenggolf/preference/ListFollowersFragment.java
  app/src/main/java/ch/epfl/sweng/swenggolf/profile/EditProfileFragment.java
  app/src/main/java/ch/epfl/sweng/swenggolf/profile/ProfileFragment.java
  app/src/main/java/ch/epfl/sweng/swenggolf/profile/User.java
  app/src/main/java/ch/epfl/sweng/swenggolf/statistics/StatisticsFragment.java
  app/src/main/java/ch/epfl/sweng/swenggolf/storage/FakeStorage.java
  app/src/main/java/ch/epfl/sweng/swenggolf/tools/FragmentConverter.java
  app/src/main/res/layout/activity_edit_profile.xml
  app/src/main/res/layout/activity_leaderboard.xml
  app/src/main/res/layout/activity_list_offer.xml
  app/src/main/res/layout/activity_messaging.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/menu/menu_drawer.xml
Labels: bug, improvement
