Repository SwengGolfTeam/Sweng_Golf, pull requests merged in 2018-10, with the labels that each got.

#60 Remove FakeUserDB, refactor code
  README.md
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/WaitingActivityTest.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/FakeUserDatabase.java
  app/src/main/res/layout/activity_fake_gallery.xml
  app/src/test/java/ch/epfl/sweng/swenggolf/ConfigTest.java
  app/src/test/java/ch/epfl/sweng/swenggolf/DbErrorTest.java
  app/src/test/java/ch/epfl/sweng/swenggolf/FakeDatabaseTest.java
  app/src/test/java/ch/epfl/sweng/swenggolf/ListOfferAdapterTest.java
  app/src/test/java/ch/epfl/sweng/swenggolf/OfferTest.java
  app/src/test/java/ch/epfl/sweng/swenggolf/PreferenceAdapterTest.java
  app/src/test/java/ch/epfl/sweng/swenggolf/TestHelper.java
  app/src/test/java/ch/epfl/sweng/swenggolf/UserTest.java
Labels: code-coverage

#62 Fb change database
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/CreateOfferActivityTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/FakeFirebaseDatabase.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/ListOfferActivityTest.java
  app/src/main/java/ch/epfl/sweng/swenggolf/User.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/DatabaseConnection.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/ValueListener.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/CreateOfferActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/ListOfferActivity.java
Labels: improvement

#66 add test for Database.java file
  app/src/test/java/ch/epfl/sweng/swenggolf/DatabaseTest.java
Labels: code coverage

#69 Complete the ProfileActivityTest + Add Database Stuff
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/ProfileActivityTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/WaitingActivityTest.java
  app/src/main/java/ch/epfl/sweng/swenggolf/Config.java
  app/src/main/java/ch/epfl/sweng/swenggolf/User.java
  app/src/main/java/ch/epfl/sweng/swenggolf/main/MainMenuActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/profile/EditProfileActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/profile/ProfileActivity.java
  app/src/main/res/layout/activity_profile.xml
Labels: code coverage

#67 Cc fake database creator
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/CreateOfferActivityTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/ListOfferActivityTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/MainMenuActivityInstrumentedTestIntents.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/PreferenceActivityTest.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/DatabaseUser.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/DbError.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/FakeDatabase.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/FilledFakeDatabase.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/CreateOfferActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/ListOfferActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/ListOfferAdapter.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/Offer.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/ShowOfferActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/tools/ThreeFieldsViewHolder.java
  app/src/main/java/ch/epfl/sweng/swenggolf/tools/ViewUserFiller.java
  app/src/test/java/ch/epfl/sweng/swenggolf/DbErrorTest.java
  app/src/test/java/ch/epfl/sweng/swenggolf/ListOfferAdapterTest.java
  app/src/test/java/ch/epfl/sweng/swenggolf/OfferTest.java
Labels: improvement

#75 Fix wrong username getter in ListOffersAdapter
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/ListOfferActivityTest.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/ListOfferAdapter.java
Labels: bug

#87 New Storage architecture and profile picture modification
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/CreateOfferActivityTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/DeleteOfferTest.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/FakeFirebaseStorage.java
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/ProfileActivityTest.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/FakeDatabase.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/StorageConnection.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/CreateOfferActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/Offer.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/ShowOfferActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/profile/EditProfileActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/storage/FakeStorage.java
  app/src/main/java/ch/epfl/sweng/swenggolf/storage/FireStorage.java
  app/src/main/java/ch/epfl/sweng/swenggolf/storage/Storage.java
  app/src/main/res/layout/activity_create_user.xml
  app/src/main/res/layout/activity_edit_profile.xml
  app/src/main/res/layout/activity_list_offer.xml
  app/src/main/res/layout/activity_main_menu.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/activity_show_offer.xml
  app/src/main/res/layout/activity_waiting.xml
  app/src/main/res/layout/layout_header.xml
  app/src/main/res/layout/offers_list_row.xml
  app/src/test/java/ch/epfl/sweng/swenggolf/DatabaseTest.java
  app/src/test/java/ch/epfl/sweng/swenggolf/DbErrorTest.java
  app/src/test/java/ch/epfl/sweng/swenggolf/FakeStorageTest.java
  app/src/test/java/ch/epfl/sweng/swenggolf/FireDatabaseTest.java
  app/src/test/java/ch/epfl/sweng/swenggolf/FireStorageTest.java
Labels: enhancement

#88 Fb add categories to offers
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/ListOfferActivityTest.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/Database.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/FakeDatabase.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/FireDatabase.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/Category.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/CreateOfferActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/ListOfferActivity.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/Offer.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/ShowOfferActivity.java
  app/src/main/res/layout/activity_create_offer.xml
  app/src/main/res/layout/activity_list_offer.xml
  app/src/main/res/layout/activity_show_offer.xml
  app/src/main/res/layout/activity_waiting.xml
  app/src/main/res/layout/switch_item.xml
  app/src/main/res/menu/menu_list_offers.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/test/java/ch/epfl/sweng/swenggolf/DatabaseTest.java
  app/src/test/java/ch/epfl/sweng/swenggolf/FireDatabaseTest.java
Labels: enhancement

#91 Hf correct tag when create offer with image
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/CreateOfferActivityTest.java
  app/src/main/java/ch/epfl/sweng/swenggolf/database/FilledFakeDatabase.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/Offer.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/ShowOfferActivity.java
  app/src/test/java/ch/epfl/sweng/swenggolf/FireDatabaseTest.java
Labels: bug

#95 Fix bug with deleting offer without image
  app/src/androidTest/java/ch/epfl/sweng/swenggolf/DeleteOfferTest.java
  app/src/main/java/ch/epfl/sweng/swenggolf/offer/ShowOfferActivity.java
  app/src/main/res/layout/activity_create_offer.xml
  app/src/main/res/values/strings.xml
Labels: bug
